name: CI to Docker Hub 

on:
  push:
    branches:
      - 'master'
    tags:
      - "v*.*.*"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_WIF_ID: ${{ secrets.GCP_WIF_ID }}
  GCP_WI_POOL_NAME: my-pool
  GCP_WI_PROVIDER_NAME: my-provider
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simple-whale-demo/simple-whale-demo:latest

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2.1.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/${{ env.GCP_WIF_ID }}/locations/global/workloadIdentityPools/${{ env.GCP_WI_POOL_NAME }}/providers/${{ env.GCP_WI_PROVIDER_NAME }}
          service_account: github-action@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Authorize Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

