name: runGcloud
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/676804139195/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-action@radiant-micron-341302.iam.gserviceaccount.com'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Describe my-service-account
        run: gcloud iam service-accounts describe 'github-action@radiant-micron-341302.iam.gserviceaccount.com'

